---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: grafana-gateway
  namespace: monitoring
spec:
  gatewayClassName: nodeipamlb-gateway-class
  listeners:
  - protocol: HTTP
    port: 80
    name: grafana-gateway
    hostname: grafana.k8s.notsodefault.ca
#  - protocol: HTTPS
#    port: 443
#    name: grafana-gateway-tls
#    hostname: argo.k8s.notsodefault.ca
#  tls:
    # Synced by OP
#    certificateRefs:
#      - kind: Secret
#        name: grafana-server-tls

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-route
  namespace: monitoring
spec:
  hostnames:
    - grafana.k8s.notsodefault.ca
  parentRefs:
    - name: grafana-gateway
  rules:
  - backendRefs:
    - name: kube-prometheus-stack-grafana
      port: 80
    matches:
      - path:
          type: PathPrefix
          value: /

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: prometheus-gateway
  namespace: monitoring
spec:
  gatewayClassName: nodeipamlb-gateway-class
  listeners:
  - protocol: HTTP
    port: 80
    name: prometheus-gateway
    hostname: prometheus.k8s.notsodefault.ca
#  - protocol: HTTPS
#    port: 443
#    name: prometheus-gateway-tls
#    hostname: argo.k8s.notsodefault.ca
#  tls:
    # Synced by OP
#    certificateRefs:
#      - kind: Secret
#        name: prometheus-server-tls
