---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-route
  namespace: monitoring
spec:
  hostnames:
    - grafana.k8s.notsodefault.ca
  parentRefs:
    - name: l2-gateway
      sectionName: grafana-listener
      namespace: kube-system
  rules:
    - backendRefs:
        - name: kube-prometheus-stack-grafana
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
#---
#apiVersion: gateway.networking.k8s.io/v1
#kind: HTTPRoute
#metadata:
#  name: prometheus-route
#  namespace: monitoring
#spec:
#  hostnames:
#    - prometheus.k8s.notsodefault.ca
#  parentRefs:
#    - name: l2-gateway
#      sectionName: prometheus-listener
#      namespace: kube-system
#  rules:
#    - backendRefs:
#        - name: kube-prometheus-stack-prometheus
#          port: 9090
#      matches:
#        - path:
#            type: PathPrefix
#            value: /
